#
# A Small World is a curated 2.5D Minecraft experience.
# Copyright (C) 2021 Dreta / Gabriel Leen
#
# A Small World is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# A Small World is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with A Small World.  If not, see <https://www.gnu.org/licenses/>.
#

# Configuration related to scenes.
scene:
  # The block type of the walls of scenes. See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  # for a list of possible block types.
  wall: BROWN_TERRACOTTA

  # The default scene to start from when a player uses
  # /aswscene enter.
  default-scene: 0

  # The location that the player will be teleported to
  # once they leave.
  leave-location:
    ==: org.bukkit.Location # Do not modify this line
    world: world # Name of the world
    x: 0
    y: 0
    z: 0

  # Configuration related to portals.
  portal:
    # The maximum amount of blocks allowed within one portal.
    # Adding way too much blocks in a portal could cause:
    #  * High server memory consumption due to portal caching
    #  * Extreme client lag when highlighting a portal due to too many entities being sent
    #  * Overall worse performance
    max-blocks: 10

    # Delay before teleporting the player after they've
    # stepped on the portal, in milliseconds.
    delay: 500

    # You can highlight a portal with /aswportal highlight.
    # This option sets how long the highlight will last for
    # in seconds.
    highlight-duration: 20

    # Before reaching the final location, the player can be
    # teleported into a "load screen" where information about
    # the destination can be displayed. You can configure whether
    # to enable the load screen for each individual portals.
    load-screen:
      # How long the load screen should last.
      duration: 500

      # When the player is on the load screen, titles can be
      # displayed showing the information about the destination.
      # You can configure them here.
      #
      # The title, subtitle and actionbar are formatted as Minecraft
      # chat components. You still use legacy string formatting with
      # &-colors, but with the new components system, you can create
      # fancy effects like custom RGB color, custom fonts and
      # click/hover effects. For examples, see [ct1], [ct2] and [ct3]
      # below.
      #
      # Available placeholders:
      # * {NAME}: The raw name of the player
      # * {DISPLAY_NAME}: The display name of the player (prefix+name+suffix)
      # * {TARGET_NAME}: The name of the target scene
      title:
        title:
          text: ""
        subtitle:
          text: ""
        actionbar:
          text: ""

# This is a demo chat component that says "Hello, world!"
# with a custom RGB color.
ct1:
  text: "Hello, world!"
  color: "#abcdef"

# This is a demo chat component that says "Hello, world!",
# opens a website when clicked, and shows "Hi!" when hovered over.
ct2:
  text: "Hello, world!"
  clickEvent:
    action: "open_url"
    value: "https://example.org"
  hoverEvent:
    action: "show_text"
    value:
      text: "Hi!"
      color: "#abcdef"

# This is a demo chat component with multiple components within
# it.
ct3:
  - text: "Hello, "
    color: "#00bbff"
  - text: "world!"
    color: "#ffeb0f"
